export const SalutationPhrases = {
  pt_br: [
    'Oi',
    'Bom dia.',
    'Boa tarde.',
    'Boa noite.',
    'Tudo bem?',
    'Como está?',
    'Estou bem. E você?',
    'Bem.',
    'Obrigado.',
    'Com licença.',
    'Só um momento.',
    'Desculpa.',
    'Por favor.',
  ],
  ht_hat: [
    'Bonjou bonswa',
    'Bonjou',
    'Bonswa',
    'Bonswa',
    'Tout bagay byen?',
    'Koman ou ye?',
    'Mwen byen ou menm?',
    'Byen',
    'Mèsi',
    'Eskize',
    'Yon titan',
    'Eskise padon',
    'silvouplè',
  ],
};

export const AirportAndBusStationPhrases = {
  pt_br: [
    'Onde fica a saída?',
    'Onde compro passagens?',
    'Seus documentos por gentileza?',
    'Onde eu retiro minha bagagem?',
    'Aqui está meu passaporte.',
    'Quanto tempo dura o voo?',
    'Qual o número do seu assento?',
    'O voo está atrasado.',
    'Embarque próximo.',
    'Embarque imediato.',
    'Essa mala serve como bagagem de mão?',
    'Posso conseguir um assento na janela?',
    'Vou me hospedar no hotel...',
    'Seu voo foi cancelado.',
  ],
  ht_hat: [
    'Ki kote soti a ye?',
    'Ki kote mwen ka achte biyè?',
    'Dokiman ou silvouplè?',
    'Ki kote map jwenn valiz mwen?',
    'Isit la paspò mwen ye?',
    'Konbyen tan vòl la ye?',
    'Ki kantite plas ou ye?',
    'Vòl la anreta.',
    'Pansyon ki tou pre.',
    'Anbakman rapid.',
    'Valiz sa a sèvi kòm bagaj men?',
    'Èske mwen ka jwenn yon chèz fenèt?',
    'Mwen rete nan otèl la...',
    'Vòl ou te anile.',
  ],
};

export const LocationPhrases = {
  pt_br: [
    'Qual nome dessa cidade?',
    'Onde fica ...?',
    'Onde encontro um restaurante?',
    'Onde encontro um hotel?',
    'Onde fica a rodoviária?',
    'Poderia emprestar o celular para uma ligação?',
    'Preciso recarregar a bateria do celular.',
    'Preciso comprar créditos para ligação do celular.',
  ],
  ht_hat: [
    'Ki non vil sa a ye?',
    'Ki kote...?',
    'Ki kote mwen jwenn yon restoran?',
    'Ki kote mwen ka jwenn yon otèl?',
    'Ki kote estasyon otobis la ye?',
    'Èske ou ta ka prete telefòn selilè ou pou yon apèl?',
    'Mwen bezwen rechaje batri telefòn selilè a.',
    'Mwen bezwen achte kredi pou apèl nan telefòn selilè.',
  ],
};

export const TransportPhrases = {
  pt_br: [
    'Quanto custa?',
    'Onde eu posso encontrar um ponto de ônibus?',
    'Onde posso conseguir um táxi?',
    'Que horas o ônibus/trem/avião sai?',
    'Esse assento está ocupado.',
  ],
  ht_hat: [
    'Konbyen?',
    'Ki kote mwen ka jwenn yon estasyon otobis?',
    'Ki kote mwen ka jwenn yon taksi?',
    'Ki lè otobis/tren/avyon an kite?',
    'Èske plas sa a okipe?',
  ],
};

export const InHotelPhrases = {
  pt_br: [
    'Quanto custa um quarto?',
    'Tem um quarto disponível?',
    'O café da manhã está incluso?',
    'Você tem serviço de quarto?',
    'Que horas o almoço é servido?',
    'Qual a senha da wi-fi?',
    'Eu tenho uma reserva no nome de...',
    'Nós precisamos de mais toalhas/cobertores/shampoo/sabonete.',
  ],
  ht_hat: [
    'Konbyen yon chanm pri?',
    'Ou gen yon chanm ki disponib?',
    'Èske dejene enkli?',
    'Ou gen sèvis chanm nan?',
    'Ki lè yo sèvi manje midi?',
    'Ki sa ki se modpas la wifi?',
    'Mwen gen yon rezèvasyon nan non...',
    'Nou bezwen plis sèvyèt/kouvèti/chanpou/savon.',
  ],
};
